version: '3'

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=somepassword
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    volumes:
      - gitea_data:/data

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD=rootpassword
      MYSQL_DATABASE=gitea
      MYSQL_USER=gitea
      MYSQL_PASSWORD=somepassword
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certs:/etc/nginx/certs
      ports:
        - "80:80"
        - "443:443"
volumes:
  gitea_data:
  mysql_data:
